const allCountries = [
  {
    name: 'Afghanistan',
    regions: [
      'asia',
    ],
    iso2: 'af',
    dialCode: '+93',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Albania',
    regions: [
      'europe',
    ],
    iso2: 'al',
    dialCode: '+355',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Algeria',
    regions: [
      'africa',
      'north-africa',
    ],
    iso2: 'dz',
    dialCode: '+213',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'American Samoa',
    regions: [
      'oceania',
    ],
    iso2: 'as',
    dialCode: '+1684',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Andorra',
    regions: [
      'europe',
    ],
    iso2: 'ad',
    dialCode: '+376',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Angola',
    regions: [
      'africa',
    ],
    iso2: 'ao',
    dialCode: '+244',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Anguilla',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'ai',
    dialCode: '+1264',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Antigua and Barbuda',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'ag',
    dialCode: '+1268',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Argentina',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'ar',
    dialCode: '+54',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Armenia',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'am',
    dialCode: '+374',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Aruba',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'aw',
    dialCode: '+297',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Australia',
    regions: [
      'oceania',
    ],
    iso2: 'au',
    dialCode: '+61',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Austria',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'at',
    dialCode: '+43',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Azerbaijan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'az',
    dialCode: '+994',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bahamas',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'bs',
    dialCode: '+1242',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bahrain',
    regions: [
      'middle-east',
    ],
    iso2: 'bh',
    dialCode: '+973',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bangladesh',
    regions: [
      'asia',
    ],
    iso2: 'bd',
    dialCode: '+880',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Barbados',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'bb',
    dialCode: '+1246',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Belarus',
    regions: [
      'europe',
      'ex-ussr',
    ],
    iso2: 'by',
    dialCode: '+375',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Belgium',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'be',
    dialCode: '+32',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Belize',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'bz',
    dialCode: '+501',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Benin',
    regions: [
      'africa',
    ],
    iso2: 'bj',
    dialCode: '+229',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bermuda',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'bm',
    dialCode: '+1441',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bhutan',
    regions: [
      'asia',
    ],
    iso2: 'bt',
    dialCode: '+975',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bolivia',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'bo',
    dialCode: '+591',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bosnia and Herzegovina',
    regions: [
      'europe',
    ],
    iso2: 'ba',
    dialCode: '+387',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Botswana',
    regions: [
      'africa',
    ],
    iso2: 'bw',
    dialCode: '+267',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Brazil',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'br',
    dialCode: '+55',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'British Indian Ocean Territory',
    regions: [
      'asia',
    ],
    iso2: 'io',
    dialCode: '+246',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'British Virgin Islands',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'vg',
    dialCode: '+1284',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Brunei',
    regions: [
      'asia',
    ],
    iso2: 'bn',
    dialCode: '+673',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Bulgaria',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'bg',
    dialCode: '+359',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Burkina Faso',
    regions: [
      'africa',
    ],
    iso2: 'bf',
    dialCode: '+226',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Burundi',
    regions: [
      'africa',
    ],
    iso2: 'bi',
    dialCode: '+257',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Cambodia',
    regions: [
      'asia',
    ],
    iso2: 'kh',
    dialCode: '+855',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Cameroon',
    regions: [
      'africa',
    ],
    iso2: 'cm',
    dialCode: '+237',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1',
    priority: 1,
    hasAreaCodes: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1204',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1236',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1249',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1250',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1289',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1306',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1343',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1365',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1387',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1403',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1416',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1418',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1431',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1437',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1438',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1450',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1506',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1514',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1519',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1548',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1579',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1581',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1587',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1604',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1613',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1639',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1647',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1672',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1705',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1709',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1742',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1778',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1780',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1782',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1807',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1819',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1825',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1867',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1873',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1902',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'ca',
    dialCode: '+1905',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Cape Verde',
    regions: [
      'africa',
    ],
    iso2: 'cv',
    dialCode: '+238',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Caribbean Netherlands',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'bq',
    dialCode: '+599',
    priority: 1,
    hasAreaCodes: false,
  },
  {
    name: 'Cayman Islands',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'ky',
    dialCode: '+1345',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Central African Republic',
    regions: [
      'africa',
    ],
    iso2: 'cf',
    dialCode: '+236',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Chad',
    regions: [
      'africa',
    ],
    iso2: 'td',
    dialCode: '+235',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Chile',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'cl',
    dialCode: '+56',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'China',
    regions: [
      'asia',
    ],
    iso2: 'cn',
    dialCode: '+86',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Colombia',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'co',
    dialCode: '+57',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Comoros',
    regions: [
      'africa',
    ],
    iso2: 'km',
    dialCode: '+269',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Congo',
    regions: [
      'africa',
    ],
    iso2: 'cd',
    dialCode: '+243',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Congo',
    regions: [
      'africa',
    ],
    iso2: 'cg',
    dialCode: '+242',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Cook Islands',
    regions: [
      'oceania',
    ],
    iso2: 'ck',
    dialCode: '+682',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Costa Rica',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'cr',
    dialCode: '+506',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Côte d’Ivoire',
    regions: [
      'africa',
    ],
    iso2: 'ci',
    dialCode: '+225',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Croatia',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'hr',
    dialCode: '+385',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Cuba',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'cu',
    dialCode: '+53',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Curaçao',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'cw',
    dialCode: '+599',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Cyprus',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'cy',
    dialCode: '+357',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Czech Republic',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'cz',
    dialCode: '+420',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Denmark',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'dk',
    dialCode: '+45',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Djibouti',
    regions: [
      'africa',
    ],
    iso2: 'dj',
    dialCode: '+253',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Dominica',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'dm',
    dialCode: '+1767',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Dominican Republic',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'do',
    dialCode: '+1',
    priority: 2,
    hasAreaCodes: true,
  },
  {
    name: 'Dominican Republic',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'do',
    dialCode: '+1809',
    priority: 2,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Dominican Republic',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'do',
    dialCode: '+1829',
    priority: 2,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Dominican Republic',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'do',
    dialCode: '+1849',
    priority: 2,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Ecuador',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'ec',
    dialCode: '+593',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Egypt',
    regions: [
      'africa',
      'north-africa',
    ],
    iso2: 'eg',
    dialCode: '+20',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'El Salvador',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'sv',
    dialCode: '+503',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Equatorial Guinea',
    regions: [
      'africa',
    ],
    iso2: 'gq',
    dialCode: '+240',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Eritrea',
    regions: [
      'africa',
    ],
    iso2: 'er',
    dialCode: '+291',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Estonia',
    regions: [
      'europe',
      'european-union',
      'ex-ussr',
    ],
    iso2: 'ee',
    dialCode: '+372',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Ethiopia',
    regions: [
      'africa',
    ],
    iso2: 'et',
    dialCode: '+251',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Falkland Islands',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'fk',
    dialCode: '+500',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Faroe Islands',
    regions: [
      'europe',
    ],
    iso2: 'fo',
    dialCode: '+298',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Fiji',
    regions: [
      'oceania',
    ],
    iso2: 'fj',
    dialCode: '+679',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Finland',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'fi',
    dialCode: '+358',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'France',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'fr',
    dialCode: '+33',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'French Guiana',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'gf',
    dialCode: '+594',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'French Polynesia',
    regions: [
      'oceania',
    ],
    iso2: 'pf',
    dialCode: '+689',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Gabon',
    regions: [
      'africa',
    ],
    iso2: 'ga',
    dialCode: '+241',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Gambia',
    regions: [
      'africa',
    ],
    iso2: 'gm',
    dialCode: '+220',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Georgia',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'ge',
    dialCode: '+995',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Germany',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'de',
    dialCode: '+49',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Ghana',
    regions: [
      'africa',
    ],
    iso2: 'gh',
    dialCode: '+233',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Gibraltar',
    regions: [
      'europe',
    ],
    iso2: 'gi',
    dialCode: '+350',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Greece',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'gr',
    dialCode: '+30',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Greenland',
    regions: [
      'america',
    ],
    iso2: 'gl',
    dialCode: '+299',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Grenada',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'gd',
    dialCode: '+1473',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Guadeloupe',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'gp',
    dialCode: '+590',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Guam',
    regions: [
      'oceania',
    ],
    iso2: 'gu',
    dialCode: '+1671',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Guatemala',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'gt',
    dialCode: '+502',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Guinea',
    regions: [
      'africa',
    ],
    iso2: 'gn',
    dialCode: '+224',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Guinea-Bissau',
    regions: [
      'africa',
    ],
    iso2: 'gw',
    dialCode: '+245',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Guyana',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'gy',
    dialCode: '+592',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Haiti',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'ht',
    dialCode: '+509',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Honduras',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'hn',
    dialCode: '+504',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Hong Kong',
    regions: [
      'asia',
    ],
    iso2: 'hk',
    dialCode: '+852',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Hungary',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'hu',
    dialCode: '+36',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Iceland',
    regions: [
      'europe',
    ],
    iso2: 'is',
    dialCode: '+354',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'India',
    regions: [
      'asia',
    ],
    iso2: 'in',
    dialCode: '+91',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Indonesia',
    regions: [
      'asia',
    ],
    iso2: 'id',
    dialCode: '+62',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Iran',
    regions: [
      'middle-east',
    ],
    iso2: 'ir',
    dialCode: '+98',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Iraq',
    regions: [
      'middle-east',
    ],
    iso2: 'iq',
    dialCode: '+964',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Ireland',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'ie',
    dialCode: '+353',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Israel',
    regions: [
      'middle-east',
    ],
    iso2: 'il',
    dialCode: '+972',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Italy',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'it',
    dialCode: '+39',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Jamaica',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'jm',
    dialCode: '+1876',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Japan',
    regions: [
      'asia',
    ],
    iso2: 'jp',
    dialCode: '+81',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Jordan',
    regions: [
      'middle-east',
    ],
    iso2: 'jo',
    dialCode: '+962',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7',
    priority: 1,
    hasAreaCodes: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7313',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7327',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+77172',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7312',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+773622',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7321',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7324',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7336',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7318',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7315',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7325',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7311',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7326',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kz',
    dialCode: '+7310',
    priority: 1,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kenya',
    regions: [
      'africa',
    ],
    iso2: 'ke',
    dialCode: '+254',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Kiribati',
    regions: [
      'oceania',
    ],
    iso2: 'ki',
    dialCode: '+686',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Kuwait',
    regions: [
      'middle-east',
    ],
    iso2: 'kw',
    dialCode: '+965',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Kyrgyzstan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'kg',
    dialCode: '+996',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Laos',
    regions: [
      'asia',
    ],
    iso2: 'la',
    dialCode: '+856',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Latvia',
    regions: [
      'europe',
      'european-union',
      'ex-ussr',
    ],
    iso2: 'lv',
    dialCode: '+371',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Lebanon',
    regions: [
      'middle-east',
    ],
    iso2: 'lb',
    dialCode: '+961',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Lesotho',
    regions: [
      'africa',
    ],
    iso2: 'ls',
    dialCode: '+266',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Liberia',
    regions: [
      'africa',
    ],
    iso2: 'lr',
    dialCode: '+231',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Libya',
    regions: [
      'africa',
      'north-africa',
    ],
    iso2: 'ly',
    dialCode: '+218',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Liechtenstein',
    regions: [
      'europe',
    ],
    iso2: 'li',
    dialCode: '+423',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Lithuania',
    regions: [
      'europe',
      'european-union',
      'ex-ussr',
    ],
    iso2: 'lt',
    dialCode: '+370',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Luxembourg',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'lu',
    dialCode: '+352',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Macau',
    regions: [
      'asia',
    ],
    iso2: 'mo',
    dialCode: '+853',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Macedonia',
    regions: [
      'europe',
    ],
    iso2: 'mk',
    dialCode: '+389',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Madagascar',
    regions: [
      'africa',
    ],
    iso2: 'mg',
    dialCode: '+261',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Malawi',
    regions: [
      'africa',
    ],
    iso2: 'mw',
    dialCode: '+265',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Malaysia',
    regions: [
      'asia',
    ],
    iso2: 'my',
    dialCode: '+60',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Maldives',
    regions: [
      'asia',
    ],
    iso2: 'mv',
    dialCode: '+960',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Mali',
    regions: [
      'africa',
    ],
    iso2: 'ml',
    dialCode: '+223',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Malta',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'mt',
    dialCode: '+356',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Marshall Islands',
    regions: [
      'oceania',
    ],
    iso2: 'mh',
    dialCode: '+692',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Martinique',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'mq',
    dialCode: '+596',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Mauritania',
    regions: [
      'africa',
    ],
    iso2: 'mr',
    dialCode: '+222',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Mauritius',
    regions: [
      'africa',
    ],
    iso2: 'mu',
    dialCode: '+230',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Mexico',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'mx',
    dialCode: '+52',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Micronesia',
    regions: [
      'oceania',
    ],
    iso2: 'fm',
    dialCode: '+691',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Moldova',
    regions: [
      'europe',
    ],
    iso2: 'md',
    dialCode: '+373',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Monaco',
    regions: [
      'europe',
    ],
    iso2: 'mc',
    dialCode: '+377',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Mongolia',
    regions: [
      'asia',
    ],
    iso2: 'mn',
    dialCode: '+976',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Montenegro',
    regions: [
      'europe',
    ],
    iso2: 'me',
    dialCode: '+382',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Montserrat',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'ms',
    dialCode: '+1664',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Morocco',
    regions: [
      'africa',
      'north-africa',
    ],
    iso2: 'ma',
    dialCode: '+212',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Mozambique',
    regions: [
      'africa',
    ],
    iso2: 'mz',
    dialCode: '+258',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Myanmar',
    regions: [
      'asia',
    ],
    iso2: 'mm',
    dialCode: '+95',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Namibia',
    regions: [
      'africa',
    ],
    iso2: 'na',
    dialCode: '+264',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Nauru',
    regions: [
      'africa',
    ],
    iso2: 'nr',
    dialCode: '+674',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Nepal',
    regions: [
      'asia',
    ],
    iso2: 'np',
    dialCode: '+977',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Netherlands',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'nl',
    dialCode: '+31',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'New Caledonia',
    regions: [
      'oceania',
    ],
    iso2: 'nc',
    dialCode: '+687',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'New Zealand',
    regions: [
      'oceania',
    ],
    iso2: 'nz',
    dialCode: '+64',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Nicaragua',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'ni',
    dialCode: '+505',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Niger',
    regions: [
      'africa',
    ],
    iso2: 'ne',
    dialCode: '+227',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Nigeria',
    regions: [
      'africa',
    ],
    iso2: 'ng',
    dialCode: '+234',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Niue',
    regions: [
      'asia',
    ],
    iso2: 'nu',
    dialCode: '+683',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Norfolk Island',
    regions: [
      'oceania',
    ],
    iso2: 'nf',
    dialCode: '+672',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'North Korea',
    regions: [
      'asia',
    ],
    iso2: 'kp',
    dialCode: '+850',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Northern Mariana Islands',
    regions: [
      'oceania',
    ],
    iso2: 'mp',
    dialCode: '+1670',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Norway',
    regions: [
      'europe',
    ],
    iso2: 'no',
    dialCode: '+47',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Oman',
    regions: [
      'middle-east',
    ],
    iso2: 'om',
    dialCode: '+968',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Pakistan',
    regions: [
      'asia',
    ],
    iso2: 'pk',
    dialCode: '+92',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Palau',
    regions: [
      'oceania',
    ],
    iso2: 'pw',
    dialCode: '+680',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Palestine',
    regions: [
      'middle-east',
    ],
    iso2: 'ps',
    dialCode: '+970',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Panama',
    regions: [
      'america',
      'central-america',
    ],
    iso2: 'pa',
    dialCode: '+507',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Papua New Guinea',
    regions: [
      'oceania',
    ],
    iso2: 'pg',
    dialCode: '+675',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Paraguay',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'py',
    dialCode: '+595',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Peru',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'pe',
    dialCode: '+51',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Philippines',
    regions: [
      'asia',
    ],
    iso2: 'ph',
    dialCode: '+63',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Poland',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'pl',
    dialCode: '+48',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Portugal',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'pt',
    dialCode: '+351',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Puerto Rico',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'pr',
    dialCode: '+1',
    priority: 3,
    hasAreaCodes: true,
  },
  {
    name: 'Puerto Rico',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'pr',
    dialCode: '+1787',
    priority: 3,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Puerto Rico',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'pr',
    dialCode: '+1939',
    priority: 3,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Qatar',
    regions: [
      'middle-east',
    ],
    iso2: 'qa',
    dialCode: '+974',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Réunion',
    regions: [
      'africa',
    ],
    iso2: 're',
    dialCode: '+262',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Romania',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'ro',
    dialCode: '+40',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Russia',
    regions: [
      'europe',
      'asia',
      'ex-ussr',
    ],
    iso2: 'ru',
    dialCode: '+7',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Rwanda',
    regions: [
      'africa',
    ],
    iso2: 'rw',
    dialCode: '+250',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Saint Barthélemy',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'bl',
    dialCode: '+590',
    priority: 1,
    hasAreaCodes: false,
  },
  {
    name: 'Saint Helena',
    regions: [
      'africa',
    ],
    iso2: 'sh',
    dialCode: '+290',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Saint Kitts and Nevis',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'kn',
    dialCode: '+1869',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Saint Lucia',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'lc',
    dialCode: '+1758',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Saint Martin',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'mf',
    dialCode: '+590',
    priority: 2,
    hasAreaCodes: false,
  },
  {
    name: 'Saint Pierre and Miquelon',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'pm',
    dialCode: '+508',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'vc',
    dialCode: '+1784',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Samoa',
    regions: [
      'oceania',
    ],
    iso2: 'ws',
    dialCode: '+685',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'San Marino',
    regions: [
      'europe',
    ],
    iso2: 'sm',
    dialCode: '+378',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'São Tomé and Príncipe',
    regions: [
      'africa',
    ],
    iso2: 'st',
    dialCode: '+239',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Saudi Arabia',
    regions: [
      'middle-east',
    ],
    iso2: 'sa',
    dialCode: '+966',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Senegal',
    regions: [
      'africa',
    ],
    iso2: 'sn',
    dialCode: '+221',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Serbia',
    regions: [
      'europe',
    ],
    iso2: 'rs',
    dialCode: '+381',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Seychelles',
    regions: [
      'africa',
    ],
    iso2: 'sc',
    dialCode: '+248',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Sierra Leone',
    regions: [
      'africa',
    ],
    iso2: 'sl',
    dialCode: '+232',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Singapore',
    regions: [
      'asia',
    ],
    iso2: 'sg',
    dialCode: '+65',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Sint Maarten',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'sx',
    dialCode: '+1721',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Slovakia',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'sk',
    dialCode: '+421',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Slovenia',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'si',
    dialCode: '+386',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Solomon Islands',
    regions: [
      'oceania',
    ],
    iso2: 'sb',
    dialCode: '+677',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Somalia',
    regions: [
      'africa',
    ],
    iso2: 'so',
    dialCode: '+252',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'South Africa',
    regions: [
      'africa',
    ],
    iso2: 'za',
    dialCode: '+27',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'South Korea',
    regions: [
      'asia',
    ],
    iso2: 'kr',
    dialCode: '+82',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'South Sudan',
    regions: [
      'africa',
      'north-africa',
    ],
    iso2: 'ss',
    dialCode: '+211',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Spain',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'es',
    dialCode: '+34',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Sri Lanka',
    regions: [
      'asia',
    ],
    iso2: 'lk',
    dialCode: '+94',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Sudan',
    regions: [
      'africa',
    ],
    iso2: 'sd',
    dialCode: '+249',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Suriname',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'sr',
    dialCode: '+597',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Swaziland',
    regions: [
      'africa',
    ],
    iso2: 'sz',
    dialCode: '+268',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Sweden',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'se',
    dialCode: '+46',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Switzerland',
    regions: [
      'europe',
    ],
    iso2: 'ch',
    dialCode: '+41',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Syria',
    regions: [
      'middle-east',
    ],
    iso2: 'sy',
    dialCode: '+963',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Taiwan',
    regions: [
      'asia',
    ],
    iso2: 'tw',
    dialCode: '+886',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Tajikistan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'tj',
    dialCode: '+992',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Tanzania',
    regions: [
      'africa',
    ],
    iso2: 'tz',
    dialCode: '+255',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Thailand',
    regions: [
      'asia',
    ],
    iso2: 'th',
    dialCode: '+66',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Timor-Leste',
    regions: [
      'asia',
    ],
    iso2: 'tl',
    dialCode: '+670',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Togo',
    regions: [
      'africa',
    ],
    iso2: 'tg',
    dialCode: '+228',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Tokelau',
    regions: [
      'oceania',
    ],
    iso2: 'tk',
    dialCode: '+690',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Tonga',
    regions: [
      'oceania',
    ],
    iso2: 'to',
    dialCode: '+676',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Trinidad and Tobago',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'tt',
    dialCode: '+1868',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Tunisia',
    regions: [
      'africa',
      'north-africa',
    ],
    iso2: 'tn',
    dialCode: '+216',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Turkey',
    regions: [
      'europe',
    ],
    iso2: 'tr',
    dialCode: '+90',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Turkmenistan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'tm',
    dialCode: '+993',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Turks and Caicos Islands',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'tc',
    dialCode: '+1649',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Tuvalu',
    regions: [
      'asia',
    ],
    iso2: 'tv',
    dialCode: '+688',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'U.S. Virgin Islands',
    regions: [
      'america',
      'carribean',
    ],
    iso2: 'vi',
    dialCode: '+1340',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Uganda',
    regions: [
      'africa',
    ],
    iso2: 'ug',
    dialCode: '+256',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Ukraine',
    regions: [
      'europe',
      'ex-ussr',
    ],
    iso2: 'ua',
    dialCode: '+380',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'United Arab Emirates',
    regions: [
      'middle-east',
    ],
    iso2: 'ae',
    dialCode: '+971',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'United Kingdom',
    regions: [
      'europe',
      'european-union',
    ],
    iso2: 'gb',
    dialCode: '+44',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1',
    priority: 0,
    hasAreaCodes: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1907',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1205',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1251',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1256',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1334',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1479',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1501',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1870',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1480',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1520',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1602',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1623',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1928',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1209',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1213',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1310',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1323',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1408',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1415',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1510',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1530',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1559',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1562',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1619',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1626',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1650',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1661',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1707',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1714',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1760',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1805',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1818',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1831',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1858',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1909',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1916',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1925',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1949',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1951',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1303',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1719',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1970',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1203',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1860',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1202',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1302',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1239',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1305',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1321',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1352',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1386',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1407',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1561',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1727',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1772',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1813',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1850',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1863',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1904',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1941',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1954',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1229',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1404',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1478',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1706',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1770',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1912',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1808',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1319',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1515',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1563',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1641',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1712',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1208',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1217',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1309',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1312',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1618',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1630',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1708',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1773',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1815',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1847',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1219',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1260',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1317',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1574',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1765',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1812',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1316',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1620',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1785',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1913',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1270',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1502',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1606',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1859',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1225',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1318',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1337',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1504',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1985',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1413',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1508',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1617',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1781',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1978',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1301',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1410',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1207',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1231',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1248',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1269',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1313',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1517',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1586',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1616',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1734',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1810',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1906',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1989',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1218',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1320',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1507',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1612',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1651',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1763',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1952',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1314',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1417',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1573',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1636',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1660',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1816',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1228',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1601',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1662',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1406',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1252',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1336',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1704',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1828',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1910',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1919',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1701',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1308',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1402',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1603',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1201',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1609',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1732',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1856',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1908',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1973',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1505',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1575',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1702',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1775',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1212',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1315',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1516',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1518',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1585',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1607',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1631',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1716',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1718',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1845',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1914',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1216',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1330',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1419',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1440',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1513',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1614',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1740',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1937',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1405',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1580',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1918',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1503',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1541',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1215',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1412',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1570',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1610',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1717',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1724',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1814',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1401',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1803',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1843',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1864',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1605',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1423',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1615',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1731',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1865',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1901',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1931',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1210',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1214',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1254',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1281',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1325',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1361',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1409',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1432',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1512',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1713',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1806',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1817',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1830',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1903',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1915',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1936',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1940',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1956',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1972',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1979',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1435',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1801',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1276',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1434',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1540',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1703',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1757',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1804',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1802',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1206',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1253',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1360',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1425',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1509',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1262',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1414',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1608',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1715',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1920',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1304',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: [
      'america',
      'north-america',
    ],
    iso2: 'us',
    dialCode: '+1307',
    priority: 0,
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Uruguay',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 'uy',
    dialCode: '+598',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Uzbekistan',
    regions: [
      'asia',
      'ex-ussr',
    ],
    iso2: 'uz',
    dialCode: '+998',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Vanuatu',
    regions: [
      'oceania',
    ],
    iso2: 'vu',
    dialCode: '+678',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Vatican City',
    regions: [
      'europe',
    ],
    iso2: 'va',
    dialCode: '+39',
    priority: 1,
    hasAreaCodes: false,
  },
  {
    name: 'Venezuela',
    regions: [
      'america',
      'south-america',
    ],
    iso2: 've',
    dialCode: '+58',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Vietnam',
    regions: [
      'asia',
    ],
    iso2: 'vn',
    dialCode: '+84',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Wallis and Futuna',
    regions: [
      'oceania',
    ],
    iso2: 'wf',
    dialCode: '+681',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Yemen',
    regions: [
      'middle-east',
    ],
    iso2: 'ye',
    dialCode: '+967',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Zambia',
    regions: [
      'africa',
    ],
    iso2: 'zm',
    dialCode: '+260',
    priority: 0,
    hasAreaCodes: false,
  },
  {
    name: 'Zimbabwe',
    regions: [
      'africa',
    ],
    iso2: 'zw',
    dialCode: '+263',
    priority: 0,
    hasAreaCodes: false,
  },
]

export default allCountries
