import { ICountry } from '../types';

export const allCountries: ICountry[] = [
  {
    name: '',
    regions: [],
    iso2: 'INTL',
    dialCode: '',
    isAreaCode: false,
    hasAreaCodes: false,
  },
  {
    name: 'Afghanistan (‫افغانستان‬‎)',
    regions: ['asia'],
    iso2: 'AF',
    dialCode: '+93',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Albania (Shqipëri)',
    regions: ['europe'],
    iso2: 'AL',
    dialCode: '+355',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Algeria (‫الجزائر‬‎)',
    regions: ['africa', 'north-africa'],
    iso2: 'DZ',
    dialCode: '+213',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'American Samoa',
    regions: ['oceania'],
    iso2: 'AS',
    dialCode: '+1684',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Andorra',
    regions: ['europe'],
    iso2: 'AD',
    dialCode: '+376',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Angola',
    regions: ['africa'],
    iso2: 'AO',
    dialCode: '+244',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Anguilla',
    regions: ['america', 'carribean'],
    iso2: 'AI',
    dialCode: '+1264',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Antigua and Barbuda',
    regions: ['america', 'carribean'],
    iso2: 'AG',
    dialCode: '+1268',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Argentina',
    regions: ['america', 'south-america'],
    iso2: 'AR',
    dialCode: '+54',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Armenia (Հայաստան)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'AM',
    dialCode: '+374',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Aruba',
    regions: ['america', 'carribean'],
    iso2: 'AW',
    dialCode: '+297',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Australia',
    regions: ['oceania'],
    iso2: 'AU',
    dialCode: '+61',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Austria (Österreich)',
    regions: ['europe', 'european-union'],
    iso2: 'AT',
    dialCode: '+43',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Azerbaijan (Azərbaycan)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'AZ',
    dialCode: '+994',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bahamas',
    regions: ['america', 'carribean'],
    iso2: 'BS',
    dialCode: '+1242',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bahrain (‫البحرين‬‎)',
    regions: ['middle-east'],
    iso2: 'BH',
    dialCode: '+973',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bangladesh (বাংলাদেশ)',
    regions: ['asia'],
    iso2: 'BD',
    dialCode: '+880',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Barbados',
    regions: ['america', 'carribean'],
    iso2: 'BB',
    dialCode: '+1246',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Belarus (Беларусь)',
    regions: ['europe', 'ex-ussr'],
    iso2: 'BY',
    dialCode: '+375',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Belgium (België)',
    regions: ['europe', 'european-union'],
    iso2: 'BE',
    dialCode: '+32',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Belize',
    regions: ['america', 'central-america'],
    iso2: 'BZ',
    dialCode: '+501',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Benin (Bénin)',
    regions: ['africa'],
    iso2: 'BJ',
    dialCode: '+229',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bermuda',
    regions: ['america', 'north-america'],
    iso2: 'BM',
    dialCode: '+1441',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bhutan (འབྲུག)',
    regions: ['asia'],
    iso2: 'BT',
    dialCode: '+975',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bolivia',
    regions: ['america', 'south-america'],
    iso2: 'BO',
    dialCode: '+591',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bosnia and Herzegovina (Босна и Херцеговина)',
    regions: ['europe'],
    iso2: 'BA',
    dialCode: '+387',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Botswana',
    regions: ['africa'],
    iso2: 'BW',
    dialCode: '+267',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Brazil (Brasil)',
    regions: ['america', 'south-america'],
    iso2: 'BR',
    dialCode: '+55',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'British Indian Ocean Territory',
    regions: ['asia'],
    iso2: 'IO',
    dialCode: '+246',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'British Virgin Islands',
    regions: ['america', 'carribean'],
    iso2: 'VG',
    dialCode: '+1284',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Brunei',
    regions: ['asia'],
    iso2: 'BN',
    dialCode: '+673',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Bulgaria (България)',
    regions: ['europe', 'european-union'],
    iso2: 'BG',
    dialCode: '+359',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Burkina Faso',
    regions: ['africa'],
    iso2: 'BF',
    dialCode: '+226',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Burundi (Uburundi)',
    regions: ['africa'],
    iso2: 'BI',
    dialCode: '+257',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Cambodia (កម្ពុជា)',
    regions: ['asia'],
    iso2: 'KH',
    dialCode: '+855',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Cameroon (Cameroun)',
    regions: ['africa'],
    iso2: 'CM',
    dialCode: '+237',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1',
    hasAreaCodes: true,
    isAreaCode: false,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1204',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1236',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1249',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1250',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1289',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1306',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1343',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1365',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1387',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1403',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1416',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1418',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1431',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1437',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1438',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1450',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1506',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1514',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1519',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1548',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1579',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1581',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1587',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1604',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1613',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1639',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1647',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1672',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1705',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1709',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1742',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1778',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1780',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1782',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1807',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1819',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1825',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1867',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1873',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1902',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Canada',
    regions: ['america', 'north-america'],
    iso2: 'CA',
    dialCode: '+1905',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Cape Verde (Kabu Verdi)',
    regions: ['africa'],
    iso2: 'CV',
    dialCode: '+238',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Caribbean Netherlands',
    regions: ['america', 'carribean'],
    iso2: 'BQ',
    dialCode: '+599',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Cayman Islands',
    regions: ['america', 'carribean'],
    iso2: 'KY',
    dialCode: '+1345',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Central African Republic (République centrafricaine)',
    regions: ['africa'],
    iso2: 'CF',
    dialCode: '+236',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Chad (Tchad)',
    regions: ['africa'],
    iso2: 'TD',
    dialCode: '+235',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Chile',
    regions: ['america', 'south-america'],
    iso2: 'CL',
    dialCode: '+56',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'China (中国)',
    regions: ['asia'],
    iso2: 'CN',
    dialCode: '+86',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Colombia',
    regions: ['america', 'south-america'],
    iso2: 'CO',
    dialCode: '+57',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Comoros (‫جزر القمر‬‎)',
    regions: ['africa'],
    iso2: 'KM',
    dialCode: '+269',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)',
    regions: ['africa'],
    iso2: 'CD',
    dialCode: '+243',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Congo (Republic) (Congo-Brazzaville)',
    regions: ['africa'],
    iso2: 'CG',
    dialCode: '+242',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Cook Islands',
    regions: ['oceania'],
    iso2: 'CK',
    dialCode: '+682',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Costa Rica',
    regions: ['america', 'central-america'],
    iso2: 'CR',
    dialCode: '+506',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Côte d’Ivoire',
    regions: ['africa'],
    iso2: 'CI',
    dialCode: '+225',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Croatia (Hrvatska)',
    regions: ['europe', 'european-union'],
    iso2: 'HR',
    dialCode: '+385',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Cuba',
    regions: ['america', 'carribean'],
    iso2: 'CU',
    dialCode: '+53',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Curaçao',
    regions: ['america', 'carribean'],
    iso2: 'CW',
    dialCode: '+599',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Cyprus (Κύπρος)',
    regions: ['europe', 'european-union'],
    iso2: 'CY',
    dialCode: '+357',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Czech Republic (Česká republika)',
    regions: ['europe', 'european-union'],
    iso2: 'CZ',
    dialCode: '+420',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Denmark (Danmark)',
    regions: ['europe', 'european-union'],
    iso2: 'DK',
    dialCode: '+45',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Djibouti',
    regions: ['africa'],
    iso2: 'DJ',
    dialCode: '+253',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Dominica',
    regions: ['america', 'carribean'],
    iso2: 'DM',
    dialCode: '+1767',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Dominican Republic (República Dominicana)',
    regions: ['america', 'carribean'],
    iso2: 'DO',
    dialCode: '+1',
    hasAreaCodes: true,
    isAreaCode: false,
  },
  {
    name: 'Dominican Republic (República Dominicana)',
    regions: ['america', 'carribean'],
    iso2: 'DO',
    dialCode: '+1809',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Dominican Republic (República Dominicana)',
    regions: ['america', 'carribean'],
    iso2: 'SO',
    dialCode: '+1829',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Dominican Republic (República Dominicana)',
    regions: ['america', 'carribean'],
    iso2: 'DO',
    dialCode: '+1849',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Ecuador',
    regions: ['america', 'south-america'],
    iso2: 'EC',
    dialCode: '+593',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Egypt (‫مصر‬‎)',
    regions: ['africa', 'north-africa'],
    iso2: 'EG',
    dialCode: '+20',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'El Salvador',
    regions: ['america', 'central-america'],
    iso2: 'SV',
    dialCode: '+503',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Equatorial Guinea (Guinea Ecuatorial)',
    regions: ['africa'],
    iso2: 'GQ',
    dialCode: '+240',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Eritrea',
    regions: ['africa'],
    iso2: 'ER',
    dialCode: '+291',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Estonia (Eesti)',
    regions: ['europe', 'european-union', 'ex-ussr'],
    iso2: 'EE',
    dialCode: '+372',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Ethiopia',
    regions: ['africa'],
    iso2: 'ET',
    dialCode: '+251',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Falkland Islands (Islas Malvinas)',
    regions: ['america', 'south-america'],
    iso2: 'FK',
    dialCode: '+500',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Faroe Islands (Føroyar)',
    regions: ['europe'],
    iso2: 'FO',
    dialCode: '+298',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Fiji',
    regions: ['oceania'],
    iso2: 'FJ',
    dialCode: '+679',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Finland (Suomi)',
    regions: ['europe', 'european-union'],
    iso2: 'FI',
    dialCode: '+358',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'France',
    regions: ['europe', 'european-union'],
    iso2: 'FR',
    dialCode: '+33',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'French Guiana (Guyane française)',
    regions: ['america', 'south-america'],
    iso2: 'GF',
    dialCode: '+594',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'French Polynesia (Polynésie française)',
    regions: ['oceania'],
    iso2: 'PF',
    dialCode: '+689',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Gabon',
    regions: ['africa'],
    iso2: 'GA',
    dialCode: '+241',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Gambia',
    regions: ['africa'],
    iso2: 'GM',
    dialCode: '+220',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Georgia (საქართველო)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'GE',
    dialCode: '+995',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Germany (Deutschland)',
    regions: ['europe', 'european-union'],
    iso2: 'DE',
    dialCode: '+49',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Ghana (Gaana)',
    regions: ['africa'],
    iso2: 'GH',
    dialCode: '+233',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Gibraltar',
    regions: ['europe'],
    iso2: 'GI',
    dialCode: '+350',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Greece (Ελλάδα)',
    regions: ['europe', 'european-union'],
    iso2: 'GR',
    dialCode: '+30',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Greenland (Kalaallit Nunaat)',
    regions: ['america'],
    iso2: 'GL',
    dialCode: '+299',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Grenada',
    regions: ['america', 'carribean'],
    iso2: 'GD',
    dialCode: '+1473',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Guadeloupe',
    regions: ['america', 'carribean'],
    iso2: 'GP',
    dialCode: '+590',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Guam',
    regions: ['oceania'],
    iso2: 'GU',
    dialCode: '+1671',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Guatemala',
    regions: ['america', 'central-america'],
    iso2: 'GT',
    dialCode: '+502',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Guinea (Guinée)',
    regions: ['africa'],
    iso2: 'GN',
    dialCode: '+224',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Guinea-Bissau (Guiné Bissau)',
    regions: ['africa'],
    iso2: 'GW',
    dialCode: '+245',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Guyana',
    regions: ['america', 'south-america'],
    iso2: 'GY',
    dialCode: '+592',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Haiti',
    regions: ['america', 'carribean'],
    iso2: 'HT',
    dialCode: '+509',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Honduras',
    regions: ['america', 'central-america'],
    iso2: 'HN',
    dialCode: '+504',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Hong Kong (香港)',
    regions: ['asia'],
    iso2: 'HK',
    dialCode: '+852',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Hungary (Magyarország)',
    regions: ['europe', 'european-union'],
    iso2: 'HU',
    dialCode: '+36',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Iceland (Ísland)',
    regions: ['europe'],
    iso2: 'IS',
    dialCode: '+354',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'India (भारत)',
    regions: ['asia'],
    iso2: 'IN',
    dialCode: '+91',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Indonesia',
    regions: ['asia'],
    iso2: 'ID',
    dialCode: '+62',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Iran (‫ایران‬‎)',
    regions: ['middle-east'],
    iso2: 'IR',
    dialCode: '+98',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Iraq (‫العراق‬‎)',
    regions: ['middle-east'],
    iso2: 'IQ',
    dialCode: '+964',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Ireland',
    regions: ['europe', 'european-union'],
    iso2: 'IE',
    dialCode: '+353',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Israel (‫ישראל‬‎)',
    regions: ['middle-east'],
    iso2: 'IL',
    dialCode: '+972',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Italy (Italia)',
    regions: ['europe', 'european-union'],
    iso2: 'IT',
    dialCode: '+39',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Jamaica',
    regions: ['america', 'carribean'],
    iso2: 'JM',
    dialCode: '+1876',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Japan (日本)',
    regions: ['asia'],
    iso2: 'JP',
    dialCode: '+81',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Jordan (‫الأردن‬‎)',
    regions: ['middle-east'],
    iso2: 'JO',
    dialCode: '+962',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Russia (Россия)',
    regions: ['europe', 'asia', 'ex-ussr'],
    iso2: 'RU',
    dialCode: '+7',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7',
    hasAreaCodes: true,
    isAreaCode: false,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7313',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7327',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+77172',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7312',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+773622',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7321',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7324',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7336',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7318',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7315',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7325',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7311',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7326',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kazakhstan (Казахстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KZ',
    dialCode: '+7310',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Kenya',
    regions: ['africa'],
    iso2: 'KE',
    dialCode: '+254',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Kiribati',
    regions: ['oceania'],
    iso2: 'KI',
    dialCode: '+686',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Kuwait (‫الكويت‬‎)',
    regions: ['middle-east'],
    iso2: 'KW',
    dialCode: '+965',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Kyrgyzstan (Кыргызстан)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'KG',
    dialCode: '+996',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Laos (ລາວ)',
    regions: ['asia'],
    iso2: 'LA',
    dialCode: '+856',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Latvia (Latvija)',
    regions: ['europe', 'european-union', 'ex-ussr'],
    iso2: 'LV',
    dialCode: '+371',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Lebanon (‫لبنان‬‎)',
    regions: ['middle-east'],
    iso2: 'LB',
    dialCode: '+961',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Lesotho',
    regions: ['africa'],
    iso2: 'LS',
    dialCode: '+266',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Liberia',
    regions: ['africa'],
    iso2: 'LR',
    dialCode: '+231',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Libya (‫ليبيا‬‎)',
    regions: ['africa', 'north-africa'],
    iso2: 'LY',
    dialCode: '+218',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Liechtenstein',
    regions: ['europe'],
    iso2: 'LI',
    dialCode: '+423',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Lithuania (Lietuva)',
    regions: ['europe', 'european-union', 'ex-ussr'],
    iso2: 'LT',
    dialCode: '+370',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Luxembourg',
    regions: ['europe', 'european-union'],
    iso2: 'LU',
    dialCode: '+352',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Macau (澳門)',
    regions: ['asia'],
    iso2: 'MO',
    dialCode: '+853',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Macedonia (FYROM) (Македонија)',
    regions: ['europe'],
    iso2: 'MK',
    dialCode: '+389',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Madagascar (Madagasikara)',
    regions: ['africa'],
    iso2: 'MG',
    dialCode: '+261',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Malawi',
    regions: ['africa'],
    iso2: 'MW',
    dialCode: '+265',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Malaysia',
    regions: ['asia'],
    iso2: 'MY',
    dialCode: '+60',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Maldives',
    regions: ['asia'],
    iso2: 'MV',
    dialCode: '+960',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Mali',
    regions: ['africa'],
    iso2: 'ML',
    dialCode: '+223',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Malta',
    regions: ['europe', 'european-union'],
    iso2: 'MT',
    dialCode: '+356',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Marshall Islands',
    regions: ['oceania'],
    iso2: 'MH',
    dialCode: '+692',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Martinique',
    regions: ['america', 'carribean'],
    iso2: 'MQ',
    dialCode: '+596',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Mauritania (‫موريتانيا‬‎)',
    regions: ['africa'],
    iso2: 'MR',
    dialCode: '+222',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Mauritius (Moris)',
    regions: ['africa'],
    iso2: 'MU',
    dialCode: '+230',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Mexico (México)',
    regions: ['america', 'central-america'],
    iso2: 'MX',
    dialCode: '+52',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Micronesia',
    regions: ['oceania'],
    iso2: 'FM',
    dialCode: '+691',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Moldova (Republica Moldova)',
    regions: ['europe'],
    iso2: 'MD',
    dialCode: '+373',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Monaco',
    regions: ['europe'],
    iso2: 'MC',
    dialCode: '+377',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Mongolia (Монгол)',
    regions: ['asia'],
    iso2: 'MN',
    dialCode: '+976',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Montenegro (Crna Gora)',
    regions: ['europe'],
    iso2: 'ME',
    dialCode: '+382',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Montserrat',
    regions: ['america', 'carribean'],
    iso2: 'MS',
    dialCode: '+1664',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Morocco (‫المغرب‬‎)',
    regions: ['africa', 'north-africa'],
    iso2: 'MA',
    dialCode: '+212',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Mozambique (Moçambique)',
    regions: ['africa'],
    iso2: 'MZ',
    dialCode: '+258',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Myanmar (Burma) (မြန်မာ)',
    regions: ['asia'],
    iso2: 'MM',
    dialCode: '+95',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Namibia (Namibië)',
    regions: ['africa'],
    iso2: 'NA',
    dialCode: '+264',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Nauru',
    regions: ['africa'],
    iso2: 'NR',
    dialCode: '+674',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Nepal (नेपाल)',
    regions: ['asia'],
    iso2: 'NP',
    dialCode: '+977',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Netherlands (Nederland)',
    regions: ['europe', 'european-union'],
    iso2: 'NL',
    dialCode: '+31',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'New Caledonia (Nouvelle-Calédonie)',
    regions: ['oceania'],
    iso2: 'NC',
    dialCode: '+687',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'New Zealand',
    regions: ['oceania'],
    iso2: 'NZ',
    dialCode: '+64',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Nicaragua',
    regions: ['america', 'central-america'],
    iso2: 'NI',
    dialCode: '+505',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Niger (Nijar)',
    regions: ['africa'],
    iso2: 'NE',
    dialCode: '+227',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Nigeria',
    regions: ['africa'],
    iso2: 'NG',
    dialCode: '+234',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Niue',
    regions: ['asia'],
    iso2: 'NU',
    dialCode: '+683',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Norfolk Island',
    regions: ['oceania'],
    iso2: 'NF',
    dialCode: '+672',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'North Korea (조선 민주주의 인민 공화국)',
    regions: ['asia'],
    iso2: 'KP',
    dialCode: '+850',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Northern Mariana Islands',
    regions: ['oceania'],
    iso2: 'MP',
    dialCode: '+1670',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Norway (Norge)',
    regions: ['europe'],
    iso2: 'NO',
    dialCode: '+47',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Oman (‫عُمان‬‎)',
    regions: ['middle-east'],
    iso2: 'OM',
    dialCode: '+968',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Pakistan (‫پاکستان‬‎)',
    regions: ['asia'],
    iso2: 'PK',
    dialCode: '+92',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Palau',
    regions: ['oceania'],
    iso2: 'PW',
    dialCode: '+680',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Palestine (‫فلسطين‬‎)',
    regions: ['middle-east'],
    iso2: 'PS',
    dialCode: '+970',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Panama (Panamá)',
    regions: ['america', 'central-america'],
    iso2: 'PA',
    dialCode: '+507',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Papua New Guinea',
    regions: ['oceania'],
    iso2: 'PG',
    dialCode: '+675',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Paraguay',
    regions: ['america', 'south-america'],
    iso2: 'PY',
    dialCode: '+595',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Peru (Perú)',
    regions: ['america', 'south-america'],
    iso2: 'PE',
    dialCode: '+51',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Philippines',
    regions: ['asia'],
    iso2: 'PH',
    dialCode: '+63',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Poland (Polska)',
    regions: ['europe', 'european-union'],
    iso2: 'PL',
    dialCode: '+48',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Portugal',
    regions: ['europe', 'european-union'],
    iso2: 'PT',
    dialCode: '+351',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Puerto Rico',
    regions: ['america', 'carribean'],
    iso2: 'PR',
    dialCode: '+1',
    hasAreaCodes: true,
    isAreaCode: false,
  },
  {
    name: 'Puerto Rico',
    regions: ['america', 'carribean'],
    iso2: 'PR',
    dialCode: '+1787',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Puerto Rico',
    regions: ['america', 'carribean'],
    iso2: 'PR',
    dialCode: '+1939',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Qatar (‫قطر‬‎)',
    regions: ['middle-east'],
    iso2: 'QA',
    dialCode: '+974',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Réunion (La Réunion)',
    regions: ['africa'],
    iso2: 'RE',
    dialCode: '+262',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Romania (România)',
    regions: ['europe', 'european-union'],
    iso2: 'RO',
    dialCode: '+40',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Rwanda',
    regions: ['africa'],
    iso2: 'RW',
    dialCode: '+250',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saint Barthélemy (Saint-Barthélemy)',
    regions: ['america', 'carribean'],
    iso2: 'BL',
    dialCode: '+590',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saint Helena',
    regions: ['africa'],
    iso2: 'SH',
    dialCode: '+290',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saint Kitts and Nevis',
    regions: ['america', 'carribean'],
    iso2: 'KN',
    dialCode: '+1869',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saint Lucia',
    regions: ['america', 'carribean'],
    iso2: 'LC',
    dialCode: '+1758',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saint Martin (Saint-Martin (partie française))',
    regions: ['america', 'carribean'],
    iso2: 'MF',
    dialCode: '+590',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
    regions: ['america', 'north-america'],
    iso2: 'PM',
    dialCode: '+508',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    regions: ['america', 'carribean'],
    iso2: 'VC',
    dialCode: '+1784',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Samoa',
    regions: ['oceania'],
    iso2: 'WS',
    dialCode: '+685',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'San Marino',
    regions: ['europe'],
    iso2: 'SM',
    dialCode: '+378',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'São Tomé and Príncipe (São Tomé e Príncipe)',
    regions: ['africa'],
    iso2: 'ST',
    dialCode: '+239',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    regions: ['middle-east'],
    iso2: 'SA',
    dialCode: '+966',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Senegal (Sénégal)',
    regions: ['africa'],
    iso2: 'SN',
    dialCode: '+221',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Serbia (Србија)',
    regions: ['europe'],
    iso2: 'RS',
    dialCode: '+381',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Seychelles',
    regions: ['africa'],
    iso2: 'SC',
    dialCode: '+248',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Sierra Leone',
    regions: ['africa'],
    iso2: 'SL',
    dialCode: '+232',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Singapore',
    regions: ['asia'],
    iso2: 'SG',
    dialCode: '+65',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Sint Maarten',
    regions: ['america', 'carribean'],
    iso2: 'SX',
    dialCode: '+1721',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Slovakia (Slovensko)',
    regions: ['europe', 'european-union'],
    iso2: 'SK',
    dialCode: '+421',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Slovenia (Slovenija)',
    regions: ['europe', 'european-union'],
    iso2: 'SI',
    dialCode: '+386',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Solomon Islands',
    regions: ['oceania'],
    iso2: 'SB',
    dialCode: '+677',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Somalia (Soomaaliya)',
    regions: ['africa'],
    iso2: 'SO',
    dialCode: '+252',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'South Africa',
    regions: ['africa'],
    iso2: 'ZA',
    dialCode: '+27',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'South Korea (대한민국)',
    regions: ['asia'],
    iso2: 'KR',
    dialCode: '+82',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'South Sudan (‫جنوب السودان‬‎)',
    regions: ['africa', 'north-africa'],
    iso2: 'SS',
    dialCode: '+211',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Spain (España)',
    regions: ['europe', 'european-union'],
    iso2: 'ES',
    dialCode: '+34',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Sri Lanka (ශ්‍රී ලංකාව)',
    regions: ['asia'],
    iso2: 'LK',
    dialCode: '+94',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Sudan (‫السودان‬‎)',
    regions: ['africa'],
    iso2: 'SD',
    dialCode: '+249',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Suriname',
    regions: ['america', 'south-america'],
    iso2: 'SR',
    dialCode: '+597',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Swaziland',
    regions: ['africa'],
    iso2: 'SZ',
    dialCode: '+268',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Sweden (Sverige)',
    regions: ['europe', 'european-union'],
    iso2: 'SE',
    dialCode: '+46',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Switzerland (Schweiz)',
    regions: ['europe'],
    iso2: 'CH',
    dialCode: '+41',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Syria (‫سوريا‬‎)',
    regions: ['middle-east'],
    iso2: 'SY',
    dialCode: '+963',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Taiwan (台灣)',
    regions: ['asia'],
    iso2: 'TW',
    dialCode: '+886',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Tajikistan',
    regions: ['asia', 'ex-ussr'],
    iso2: 'TJ',
    dialCode: '+992',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Tanzania',
    regions: ['africa'],
    iso2: 'TZ',
    dialCode: '+255',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Thailand (ไทย)',
    regions: ['asia'],
    iso2: 'TH',
    dialCode: '+66',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Timor-Leste',
    regions: ['asia'],
    iso2: 'TL',
    dialCode: '+670',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Togo',
    regions: ['africa'],
    iso2: 'TG',
    dialCode: '+228',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Tokelau',
    regions: ['oceania'],
    iso2: 'TK',
    dialCode: '+690',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Tonga',
    regions: ['oceania'],
    iso2: 'TO',
    dialCode: '+676',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Trinidad and Tobago',
    regions: ['america', 'carribean'],
    iso2: 'TT',
    dialCode: '+1868',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Tunisia (‫تونس‬‎)',
    regions: ['africa', 'north-africa'],
    iso2: 'TN',
    dialCode: '+216',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Turkey (Türkiye)',
    regions: ['europe'],
    iso2: 'TR',
    dialCode: '+90',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Turkmenistan',
    regions: ['asia', 'ex-ussr'],
    iso2: 'TM',
    dialCode: '+993',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Turks and Caicos Islands',
    regions: ['america', 'carribean'],
    iso2: 'TC',
    dialCode: '+1649',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Tuvalu',
    regions: ['asia'],
    iso2: 'TV',
    dialCode: '+688',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'U.S. Virgin Islands',
    regions: ['america', 'carribean'],
    iso2: 'VI',
    dialCode: '+1340',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Uganda',
    regions: ['africa'],
    iso2: 'UG',
    dialCode: '+256',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Ukraine',
    regions: ['europe', 'ex-ussr'],
    iso2: 'UA',
    dialCode: '+380',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
    regions: ['middle-east'],
    iso2: 'AE',
    dialCode: '+971',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'United Kingdom',
    regions: ['europe', 'european-union'],
    iso2: 'GB',
    dialCode: '+44',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1',
    hasAreaCodes: true,
    isAreaCode: false,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1907',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1205',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1251',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1256',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1334',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1479',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1501',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1870',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1480',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1520',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1602',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1623',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1928',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1209',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1213',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1310',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1323',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1408',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1415',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1510',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1530',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1559',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1562',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1619',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1626',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1650',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1661',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1707',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1714',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1760',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1805',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1818',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1831',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1858',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1909',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1916',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1925',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1949',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1951',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1303',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1719',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1970',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1203',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1860',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1202',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1302',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1239',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1305',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1321',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1352',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1386',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1407',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1561',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1727',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1772',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1813',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1850',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1863',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1904',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1941',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1954',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1229',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1404',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1478',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1706',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1770',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1912',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1808',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1319',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1515',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1563',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1641',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1712',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1208',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1217',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1309',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1312',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1618',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1630',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1708',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1773',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1815',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1847',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1219',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1260',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1317',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1574',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1765',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1812',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1316',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1620',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1785',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1913',

    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1270',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1502',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1606',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1859',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1225',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1318',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1337',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1504',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1985',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1413',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1508',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1617',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1781',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1978',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1301',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1410',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1207',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1231',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1248',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1269',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1313',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1517',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1586',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1616',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1734',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1810',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1906',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1989',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1218',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1320',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1507',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1612',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1651',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1763',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1952',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1314',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1417',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1573',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1636',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1660',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1816',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1228',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1601',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1662',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1406',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1252',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1336',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1704',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1828',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1910',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1919',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1701',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1308',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1402',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1603',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1201',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1609',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1732',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1856',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1908',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1973',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1505',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1575',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1702',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1775',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1212',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1315',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1516',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1518',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1585',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1607',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1631',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1716',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1718',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1845',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1914',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1216',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1330',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1419',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1440',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1513',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1614',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1740',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1937',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1405',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1580',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1918',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1503',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1541',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1215',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1412',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1570',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1610',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1717',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1724',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1814',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1401',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1803',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1843',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1864',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1605',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1423',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1615',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1731',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1865',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1901',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1931',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1210',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1214',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1254',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1281',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1325',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1361',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1409',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1432',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1512',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1713',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1806',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1817',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1830',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1903',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1915',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1936',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1940',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1956',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1972',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1979',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1435',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1801',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1276',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1434',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1540',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1703',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1757',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1804',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1802',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1206',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1253',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1360',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1425',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1509',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1262',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1414',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1608',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1715',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1920',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1304',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'United States',
    regions: ['america', 'north-america'],
    iso2: 'US',
    dialCode: '+1307',
    hasAreaCodes: true,
    isAreaCode: true,
  },
  {
    name: 'Uruguay',
    regions: ['america', 'south-america'],
    iso2: 'UY',
    dialCode: '+598',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Uzbekistan (Oʻzbekiston)',
    regions: ['asia', 'ex-ussr'],
    iso2: 'UZ',
    dialCode: '+998',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Vanuatu',
    regions: ['oceania'],
    iso2: 'VU',
    dialCode: '+678',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Vatican City (Città del Vaticano)',
    regions: ['europe'],
    iso2: 'VA',
    dialCode: '+39',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Venezuela',
    regions: ['america', 'south-america'],
    iso2: 'VE',
    dialCode: '+58',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Vietnam (Việt Nam)',
    regions: ['asia'],
    iso2: 'VN',
    dialCode: '+84',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Wallis and Futuna',
    regions: ['oceania'],
    iso2: 'WF',
    dialCode: '+681',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Yemen (‫اليمن‬‎)',
    regions: ['middle-east'],
    iso2: 'YE',
    dialCode: '+967',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Zambia',
    regions: ['africa'],
    iso2: 'ZM',
    dialCode: '+260',
    hasAreaCodes: false,
    isAreaCode: false,
  },
  {
    name: 'Zimbabwe',
    regions: ['africa'],
    iso2: 'ZW',
    dialCode: '+263',
    hasAreaCodes: false,
    isAreaCode: false,
  },
];
